<?php
/**
 * CreateOrdersResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api\Models;

use \ArrayAccess;
use \RoyalMail\ClickAndDrop\Rest\Api\ObjectSerializer;

/**
 * CreateOrdersResponse Class Doc Comment
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CreateOrdersResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'CreateOrdersResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'successCount' => 'int',
        'errorsCount' => 'int',
        'createdOrders' => '\RoyalMail\ClickAndDrop\Rest\Api\Models\CreateOrderResponse[]',
        'failedOrders' => '\RoyalMail\ClickAndDrop\Rest\Api\Models\FailedOrderResponse[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'successCount' => null,
        'errorsCount' => null,
        'createdOrders' => null,
        'failedOrders' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'successCount' => 'successCount',
        'errorsCount' => 'errorsCount',
        'createdOrders' => 'createdOrders',
        'failedOrders' => 'failedOrders'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'successCount' => 'setSuccessCount',
        'errorsCount' => 'setErrorsCount',
        'createdOrders' => 'setCreatedOrders',
        'failedOrders' => 'setFailedOrders'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'successCount' => 'getSuccessCount',
        'errorsCount' => 'getErrorsCount',
        'createdOrders' => 'getCreatedOrders',
        'failedOrders' => 'getFailedOrders'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['successCount'] = isset($data['successCount']) ? $data['successCount'] : null;
        $this->container['errorsCount'] = isset($data['errorsCount']) ? $data['errorsCount'] : null;
        $this->container['createdOrders'] = isset($data['createdOrders']) ? $data['createdOrders'] : null;
        $this->container['failedOrders'] = isset($data['failedOrders']) ? $data['failedOrders'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets successCount
     *
     * @return int
     */
    public function getSuccessCount()
    {
        return $this->container['successCount'];
    }

    /**
     * Sets successCount
     *
     * @param int $successCount successCount
     *
     * @return $this
     */
    public function setSuccessCount($successCount)
    {
        $this->container['successCount'] = $successCount;

        return $this;
    }

    /**
     * Gets errorsCount
     *
     * @return int
     */
    public function getErrorsCount()
    {
        return $this->container['errorsCount'];
    }

    /**
     * Sets errorsCount
     *
     * @param int $errorsCount errorsCount
     *
     * @return $this
     */
    public function setErrorsCount($errorsCount)
    {
        $this->container['errorsCount'] = $errorsCount;

        return $this;
    }

    /**
     * Gets createdOrders
     *
     * @return \RoyalMail\ClickAndDrop\Rest\Api\Models\CreateOrderResponse[]
     */
    public function getCreatedOrders()
    {
        return $this->container['createdOrders'];
    }

    /**
     * Sets createdOrders
     *
     * @param \RoyalMail\ClickAndDrop\Rest\Api\Models\CreateOrderResponse[] $createdOrders createdOrders
     *
     * @return $this
     */
    public function setCreatedOrders($createdOrders)
    {
        $this->container['createdOrders'] = $createdOrders;

        return $this;
    }

    /**
     * Gets failedOrders
     *
     * @return \RoyalMail\ClickAndDrop\Rest\Api\Models\FailedOrderResponse[]
     */
    public function getFailedOrders()
    {
        return $this->container['failedOrders'];
    }

    /**
     * Sets failedOrders
     *
     * @param \RoyalMail\ClickAndDrop\Rest\Api\Models\FailedOrderResponse[] $failedOrders failedOrders
     *
     * @return $this
     */
    public function setFailedOrders($failedOrders)
    {
        $this->container['failedOrders'] = $failedOrders;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


