<?php
/**
 * LabelGenerationRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api\Models;

use \ArrayAccess;
use \RoyalMail\ClickAndDrop\Rest\Api\ObjectSerializer;

/**
 * LabelGenerationRequest Class Doc Comment
 *
 * @category Class
 * @description &lt;span class&#x3D;&#39;desc response&#39;&gt;Reserved for ChannelShipper accounts only&lt;/span&gt;
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LabelGenerationRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'LabelGenerationRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'includeLabelInResponse' => 'bool',
        'includeCN' => 'bool',
        'includeReturnsLabel' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'includeLabelInResponse' => null,
        'includeCN' => null,
        'includeReturnsLabel' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'includeLabelInResponse' => 'includeLabelInResponse',
        'includeCN' => 'includeCN',
        'includeReturnsLabel' => 'includeReturnsLabel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'includeLabelInResponse' => 'setIncludeLabelInResponse',
        'includeCN' => 'setIncludeCN',
        'includeReturnsLabel' => 'setIncludeReturnsLabel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'includeLabelInResponse' => 'getIncludeLabelInResponse',
        'includeCN' => 'getIncludeCN',
        'includeReturnsLabel' => 'getIncludeReturnsLabel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['includeLabelInResponse'] = isset($data['includeLabelInResponse']) ? $data['includeLabelInResponse'] : null;
        $this->container['includeCN'] = isset($data['includeCN']) ? $data['includeCN'] : null;
        $this->container['includeReturnsLabel'] = isset($data['includeReturnsLabel']) ? $data['includeReturnsLabel'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['includeLabelInResponse'] === null) {
            $invalidProperties[] = "'includeLabelInResponse' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets includeLabelInResponse
     *
     * @return bool
     */
    public function getIncludeLabelInResponse()
    {
        return $this->container['includeLabelInResponse'];
    }

    /**
     * Sets includeLabelInResponse
     *
     * @param bool $includeLabelInResponse includeLabelInResponse
     *
     * @return $this
     */
    public function setIncludeLabelInResponse($includeLabelInResponse)
    {
        $this->container['includeLabelInResponse'] = $includeLabelInResponse;

        return $this;
    }

    /**
     * Gets includeCN
     *
     * @return bool
     */
    public function getIncludeCN()
    {
        return $this->container['includeCN'];
    }

    /**
     * Sets includeCN
     *
     * @param bool $includeCN includeCN
     *
     * @return $this
     */
    public function setIncludeCN($includeCN)
    {
        $this->container['includeCN'] = $includeCN;

        return $this;
    }

    /**
     * Gets includeReturnsLabel
     *
     * @return bool
     */
    public function getIncludeReturnsLabel()
    {
        return $this->container['includeReturnsLabel'];
    }

    /**
     * Sets includeReturnsLabel
     *
     * @param bool $includeReturnsLabel includeReturnsLabel
     *
     * @return $this
     */
    public function setIncludeReturnsLabel($includeReturnsLabel)
    {
        $this->container['includeReturnsLabel'] = $includeReturnsLabel;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


