<?php
/**
 * LabelsApi
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use RoyalMail\ClickAndDrop\Rest\Api\ApiException;
use RoyalMail\ClickAndDrop\Rest\Api\Configuration;
use RoyalMail\ClickAndDrop\Rest\Api\HeaderSelector;
use RoyalMail\ClickAndDrop\Rest\Api\ObjectSerializer;

/**
 * LabelsApi Class Doc Comment
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LabelsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getOrdersLabelAsync
     *
     * Return a single PDF file with generated label and/or associated document(s)
     *
     * @param  string $orderIdentifiers Order Identifier or several Order Identifiers separated by semicolon (required)
     * @param  string $documentType Document generation mode. When documentType is set to \&quot;postageLabel\&quot; the additional parameters below must be used. These additional parameters will be ignored when documentType is not set to \&quot;postageLabel\&quot; (required)
     * @param  bool $includeReturnsLabel Include returns label. Required when documentType is set to &#39;postageLabel&#39; (optional)
     * @param  bool $includeCN Include CN22/CN23 with label. Optional parameter. If this parameter is used the setting will override the default account behaviour specified in the \&quot;Label format\&quot; setting \&quot;Generate customs declarations with orders\&quot; (optional)
     *
     * @throws \RoyalMail\ClickAndDrop\Rest\Api\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \SplFileObject
     */
    public function getOrdersLabelAsync($orderIdentifiers, $documentType, $includeReturnsLabel = null, $includeCN = null)
    {
        list($response) = $this->getOrdersLabelAsyncWithHttpInfo($orderIdentifiers, $documentType, $includeReturnsLabel, $includeCN);
        return $response;
    }

    /**
     * Operation getOrdersLabelAsyncWithHttpInfo
     *
     * Return a single PDF file with generated label and/or associated document(s)
     *
     * @param  string $orderIdentifiers Order Identifier or several Order Identifiers separated by semicolon (required)
     * @param  string $documentType Document generation mode. When documentType is set to \&quot;postageLabel\&quot; the additional parameters below must be used. These additional parameters will be ignored when documentType is not set to \&quot;postageLabel\&quot; (required)
     * @param  bool $includeReturnsLabel Include returns label. Required when documentType is set to &#39;postageLabel&#39; (optional)
     * @param  bool $includeCN Include CN22/CN23 with label. Optional parameter. If this parameter is used the setting will override the default account behaviour specified in the \&quot;Label format\&quot; setting \&quot;Generate customs declarations with orders\&quot; (optional)
     *
     * @throws \RoyalMail\ClickAndDrop\Rest\Api\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject, HTTP status code, HTTP response headers (array of strings)
     */
    public function getOrdersLabelAsyncWithHttpInfo($orderIdentifiers, $documentType, $includeReturnsLabel = null, $includeCN = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->getOrdersLabelAsyncRequest($orderIdentifiers, $documentType, $includeReturnsLabel, $includeCN);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SplFileObject',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RoyalMail\ClickAndDrop\Rest\Api\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\RoyalMail\ClickAndDrop\Rest\Api\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getOrdersLabelAsyncAsync
     *
     * Return a single PDF file with generated label and/or associated document(s)
     *
     * @param  string $orderIdentifiers Order Identifier or several Order Identifiers separated by semicolon (required)
     * @param  string $documentType Document generation mode. When documentType is set to \&quot;postageLabel\&quot; the additional parameters below must be used. These additional parameters will be ignored when documentType is not set to \&quot;postageLabel\&quot; (required)
     * @param  bool $includeReturnsLabel Include returns label. Required when documentType is set to &#39;postageLabel&#39; (optional)
     * @param  bool $includeCN Include CN22/CN23 with label. Optional parameter. If this parameter is used the setting will override the default account behaviour specified in the \&quot;Label format\&quot; setting \&quot;Generate customs declarations with orders\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrdersLabelAsyncAsync($orderIdentifiers, $documentType, $includeReturnsLabel = null, $includeCN = null)
    {
        return $this->getOrdersLabelAsyncAsyncWithHttpInfo($orderIdentifiers, $documentType, $includeReturnsLabel, $includeCN)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getOrdersLabelAsyncAsyncWithHttpInfo
     *
     * Return a single PDF file with generated label and/or associated document(s)
     *
     * @param  string $orderIdentifiers Order Identifier or several Order Identifiers separated by semicolon (required)
     * @param  string $documentType Document generation mode. When documentType is set to \&quot;postageLabel\&quot; the additional parameters below must be used. These additional parameters will be ignored when documentType is not set to \&quot;postageLabel\&quot; (required)
     * @param  bool $includeReturnsLabel Include returns label. Required when documentType is set to &#39;postageLabel&#39; (optional)
     * @param  bool $includeCN Include CN22/CN23 with label. Optional parameter. If this parameter is used the setting will override the default account behaviour specified in the \&quot;Label format\&quot; setting \&quot;Generate customs declarations with orders\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getOrdersLabelAsyncAsyncWithHttpInfo($orderIdentifiers, $documentType, $includeReturnsLabel = null, $includeCN = null)
    {
        $returnType = '\SplFileObject';
        $request = $this->getOrdersLabelAsyncRequest($orderIdentifiers, $documentType, $includeReturnsLabel, $includeCN);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getOrdersLabelAsync'
     *
     * @param  string $orderIdentifiers Order Identifier or several Order Identifiers separated by semicolon (required)
     * @param  string $documentType Document generation mode. When documentType is set to \&quot;postageLabel\&quot; the additional parameters below must be used. These additional parameters will be ignored when documentType is not set to \&quot;postageLabel\&quot; (required)
     * @param  bool $includeReturnsLabel Include returns label. Required when documentType is set to &#39;postageLabel&#39; (optional)
     * @param  bool $includeCN Include CN22/CN23 with label. Optional parameter. If this parameter is used the setting will override the default account behaviour specified in the \&quot;Label format\&quot; setting \&quot;Generate customs declarations with orders\&quot; (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getOrdersLabelAsyncRequest($orderIdentifiers, $documentType, $includeReturnsLabel = null, $includeCN = null)
    {
        // verify the required parameter 'orderIdentifiers' is set
        if ($orderIdentifiers === null || (is_array($orderIdentifiers) && count($orderIdentifiers) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $orderIdentifiers when calling getOrdersLabelAsync'
            );
        }
        // verify the required parameter 'documentType' is set
        if ($documentType === null || (is_array($documentType) && count($documentType) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $documentType when calling getOrdersLabelAsync'
            );
        }

        $resourcePath = '/orders/{orderIdentifiers}/label';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($documentType !== null) {
            $queryParams['documentType'] = ObjectSerializer::toQueryValue($documentType);
        }
        // query params
        if ($includeReturnsLabel !== null) {
            $queryParams['includeReturnsLabel'] = ObjectSerializer::toQueryValue($includeReturnsLabel);
        }
        // query params
        if ($includeCN !== null) {
            $queryParams['includeCN'] = ObjectSerializer::toQueryValue($includeCN);
        }

        // path params
        if ($orderIdentifiers !== null) {
            $resourcePath = str_replace(
                '{' . 'orderIdentifiers' . '}',
                ObjectSerializer::toPathValue($orderIdentifiers),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/pdf', 'application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/pdf', 'application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            
            if($headers['Content-Type'] === 'application/json') {
                // \stdClass has no __toString(), so we should encode it manually
                if ($httpBody instanceof \stdClass) {
                    $httpBody = \GuzzleHttp\json_encode($httpBody);
                }
                // array has no __toString(), so we should encode it manually
                if(is_array($httpBody)) {
                    $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($httpBody));
                }
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\Query::build($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\Query::build($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
