<?php
/**
 * CreateOrderRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

/**
 * CreateOrderRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateOrderRequest
 * @package     RoyalMail\ClickAndDrop\Rest\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOrderRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateOrderRequest"
     */
    public function testCreateOrderRequest()
    {
    }

    /**
     * Test attribute "orderReference"
     */
    public function testPropertyOrderReference()
    {
    }

    /**
     * Test attribute "recipient"
     */
    public function testPropertyRecipient()
    {
    }

    /**
     * Test attribute "sender"
     */
    public function testPropertySender()
    {
    }

    /**
     * Test attribute "billing"
     */
    public function testPropertyBilling()
    {
    }

    /**
     * Test attribute "packages"
     */
    public function testPropertyPackages()
    {
    }

    /**
     * Test attribute "orderDate"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "plannedDespatchDate"
     */
    public function testPropertyPlannedDespatchDate()
    {
    }

    /**
     * Test attribute "specialInstructions"
     */
    public function testPropertySpecialInstructions()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "shippingCostCharged"
     */
    public function testPropertyShippingCostCharged()
    {
    }

    /**
     * Test attribute "otherCosts"
     */
    public function testPropertyOtherCosts()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "currencyCode"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "postageDetails"
     */
    public function testPropertyPostageDetails()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }
}
