<?php
/**
 * CreateOrderResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

/**
 * CreateOrderResponseTest Class Doc Comment
 *
 * @category    Class
 * @description CreateOrderResponse
 * @package     RoyalMail\ClickAndDrop\Rest\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateOrderResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateOrderResponse"
     */
    public function testCreateOrderResponse()
    {
    }

    /**
     * Test attribute "orderIdentifier"
     */
    public function testPropertyOrderIdentifier()
    {
    }

    /**
     * Test attribute "orderReference"
     */
    public function testPropertyOrderReference()
    {
    }

    /**
     * Test attribute "createdOn"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "orderDate"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "printedOn"
     */
    public function testPropertyPrintedOn()
    {
    }

    /**
     * Test attribute "manifestedOn"
     */
    public function testPropertyManifestedOn()
    {
    }

    /**
     * Test attribute "shippedOn"
     */
    public function testPropertyShippedOn()
    {
    }

    /**
     * Test attribute "trackingNumber"
     */
    public function testPropertyTrackingNumber()
    {
    }

    /**
     * Test attribute "label"
     */
    public function testPropertyLabel()
    {
    }
}
