<?php
/**
 * DimensionsRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

/**
 * DimensionsRequestTest Class Doc Comment
 *
 * @category    Class
 * @description It is not mandatory to include the dimensions field. If the dimensions field is included then the inner fields heightInMms, widthInMms and depthInMms must be specified with non-zero values.
 * @package     RoyalMail\ClickAndDrop\Rest\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DimensionsRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DimensionsRequest"
     */
    public function testDimensionsRequest()
    {
    }

    /**
     * Test attribute "heightInMms"
     */
    public function testPropertyHeightInMms()
    {
    }

    /**
     * Test attribute "widthInMms"
     */
    public function testPropertyWidthInMms()
    {
    }

    /**
     * Test attribute "depthInMms"
     */
    public function testPropertyDepthInMms()
    {
    }
}
