<?php
/**
 * GetOrderDetailsResourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

/**
 * GetOrderDetailsResourceTest Class Doc Comment
 *
 * @category    Class
 * @description GetOrderDetailsResource
 * @package     RoyalMail\ClickAndDrop\Rest\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class GetOrderDetailsResourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GetOrderDetailsResource"
     */
    public function testGetOrderDetailsResource()
    {
    }

    /**
     * Test attribute "orderIdentifier"
     */
    public function testPropertyOrderIdentifier()
    {
    }

    /**
     * Test attribute "orderStatus"
     */
    public function testPropertyOrderStatus()
    {
    }

    /**
     * Test attribute "createdOn"
     */
    public function testPropertyCreatedOn()
    {
    }

    /**
     * Test attribute "printedOn"
     */
    public function testPropertyPrintedOn()
    {
    }

    /**
     * Test attribute "shippedOn"
     */
    public function testPropertyShippedOn()
    {
    }

    /**
     * Test attribute "postageAppliedOn"
     */
    public function testPropertyPostageAppliedOn()
    {
    }

    /**
     * Test attribute "manifestedOn"
     */
    public function testPropertyManifestedOn()
    {
    }

    /**
     * Test attribute "orderDate"
     */
    public function testPropertyOrderDate()
    {
    }

    /**
     * Test attribute "despatchedByOtherCourierOn"
     */
    public function testPropertyDespatchedByOtherCourierOn()
    {
    }

    /**
     * Test attribute "tradingName"
     */
    public function testPropertyTradingName()
    {
    }

    /**
     * Test attribute "channel"
     */
    public function testPropertyChannel()
    {
    }

    /**
     * Test attribute "marketplaceTypeName"
     */
    public function testPropertyMarketplaceTypeName()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "aIRNumber"
     */
    public function testPropertyAIRNumber()
    {
    }

    /**
     * Test attribute "requiresExportLicense"
     */
    public function testPropertyRequiresExportLicense()
    {
    }

    /**
     * Test attribute "commercialInvoiceNumber"
     */
    public function testPropertyCommercialInvoiceNumber()
    {
    }

    /**
     * Test attribute "commercialInvoiceDate"
     */
    public function testPropertyCommercialInvoiceDate()
    {
    }

    /**
     * Test attribute "orderReference"
     */
    public function testPropertyOrderReference()
    {
    }

    /**
     * Test attribute "channelShippingMethod"
     */
    public function testPropertyChannelShippingMethod()
    {
    }

    /**
     * Test attribute "specialInstructions"
     */
    public function testPropertySpecialInstructions()
    {
    }

    /**
     * Test attribute "pickerSpecialInstructions"
     */
    public function testPropertyPickerSpecialInstructions()
    {
    }

    /**
     * Test attribute "subtotal"
     */
    public function testPropertySubtotal()
    {
    }

    /**
     * Test attribute "shippingCostCharged"
     */
    public function testPropertyShippingCostCharged()
    {
    }

    /**
     * Test attribute "orderDiscount"
     */
    public function testPropertyOrderDiscount()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "weightInGrams"
     */
    public function testPropertyWeightInGrams()
    {
    }

    /**
     * Test attribute "packageSize"
     */
    public function testPropertyPackageSize()
    {
    }

    /**
     * Test attribute "accountBatchNumber"
     */
    public function testPropertyAccountBatchNumber()
    {
    }

    /**
     * Test attribute "currencyCode"
     */
    public function testPropertyCurrencyCode()
    {
    }

    /**
     * Test attribute "shippingDetails"
     */
    public function testPropertyShippingDetails()
    {
    }

    /**
     * Test attribute "shippingInfo"
     */
    public function testPropertyShippingInfo()
    {
    }

    /**
     * Test attribute "billingInfo"
     */
    public function testPropertyBillingInfo()
    {
    }

    /**
     * Test attribute "orderLines"
     */
    public function testPropertyOrderLines()
    {
    }

    /**
     * Test attribute "tags"
     */
    public function testPropertyTags()
    {
    }
}
