<?php
/**
 * PostageDetailsRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

/**
 * PostageDetailsRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PostageDetailsRequest
 * @package     RoyalMail\ClickAndDrop\Rest\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostageDetailsRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostageDetailsRequest"
     */
    public function testPostageDetailsRequest()
    {
    }

    /**
     * Test attribute "sendNotificationsTo"
     */
    public function testPropertySendNotificationsTo()
    {
    }

    /**
     * Test attribute "serviceCode"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "serviceRegisterCode"
     */
    public function testPropertyServiceRegisterCode()
    {
    }

    /**
     * Test attribute "consequentialLoss"
     */
    public function testPropertyConsequentialLoss()
    {
    }

    /**
     * Test attribute "receiveEmailNotification"
     */
    public function testPropertyReceiveEmailNotification()
    {
    }

    /**
     * Test attribute "receiveSmsNotification"
     */
    public function testPropertyReceiveSmsNotification()
    {
    }

    /**
     * Test attribute "guaranteedSaturdayDelivery"
     */
    public function testPropertyGuaranteedSaturdayDelivery()
    {
    }

    /**
     * Test attribute "requestSignatureUponDelivery"
     */
    public function testPropertyRequestSignatureUponDelivery()
    {
    }

    /**
     * Test attribute "isLocalCollect"
     */
    public function testPropertyIsLocalCollect()
    {
    }

    /**
     * Test attribute "isDeliveryDutyPaid"
     */
    public function testPropertyIsDeliveryDutyPaid()
    {
    }

    /**
     * Test attribute "safePlace"
     */
    public function testPropertySafePlace()
    {
    }

    /**
     * Test attribute "department"
     */
    public function testPropertyDepartment()
    {
    }

    /**
     * Test attribute "aIRNumber"
     */
    public function testPropertyAIRNumber()
    {
    }

    /**
     * Test attribute "requiresExportLicense"
     */
    public function testPropertyRequiresExportLicense()
    {
    }

    /**
     * Test attribute "commercialInvoiceNumber"
     */
    public function testPropertyCommercialInvoiceNumber()
    {
    }

    /**
     * Test attribute "commercialInvoiceDate"
     */
    public function testPropertyCommercialInvoiceDate()
    {
    }
}
