<?php
/**
 * ProductItemRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  RoyalMail\ClickAndDrop\Rest\Api
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * ChannelShipper & Royal Mail Public API
 *
 * Import your orders, retrieve your orders and generate labels.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.24-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace RoyalMail\ClickAndDrop\Rest\Api;

/**
 * ProductItemRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ProductItemRequest
 * @package     RoyalMail\ClickAndDrop\Rest\Api
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ProductItemRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ProductItemRequest"
     */
    public function testProductItemRequest()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "sKU"
     */
    public function testPropertySKU()
    {
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
    }

    /**
     * Test attribute "unitValue"
     */
    public function testPropertyUnitValue()
    {
    }

    /**
     * Test attribute "unitWeightInGrams"
     */
    public function testPropertyUnitWeightInGrams()
    {
    }

    /**
     * Test attribute "customsDescription"
     */
    public function testPropertyCustomsDescription()
    {
    }

    /**
     * Test attribute "extendedCustomsDescription"
     */
    public function testPropertyExtendedCustomsDescription()
    {
    }

    /**
     * Test attribute "customsCode"
     */
    public function testPropertyCustomsCode()
    {
    }

    /**
     * Test attribute "originCountryCode"
     */
    public function testPropertyOriginCountryCode()
    {
    }

    /**
     * Test attribute "customsDeclarationCategory"
     */
    public function testPropertyCustomsDeclarationCategory()
    {
    }

    /**
     * Test attribute "requiresExportLicence"
     */
    public function testPropertyRequiresExportLicence()
    {
    }
}
